const InterestingItems = [
  { title: "90s Kid" },
  { title: "Harry Potter" },
  { title: "SoundCloud" },
  { title: "Spa" },
  { title: "Self Care" },
  { title: "Heavy Metal" },
  { title: "House Parties" },
  { title: "Gin tonic" },
  { title: "Gymnastics" },
  { title: "Hot Yoga" },
  { title: "Meditation" },
  { title: "Sushi" },
  { title: "Spotify" },
  { title: "Hockey" },
  { title: "Basketball" },
  { title: "Slam Poetry" },
  { title: "Home Workout" },
  { title: "Theater" },
  { title: "Cafe hopping" },
  { title: "Aquarium" },
  { title: "Sneakers" },
  { title: "Instagram" },
  { title: "Hot Springs" },
  { title: "Walking" },
  { title: "Running" },
  { title: "Travel" },
  { title: "Language Exchange" },
  { title: "Movies" },
  { title: "Guitarists" },
  { title: "Social Development" },
  { title: "Gym" },
  { title: "Social Media" },
  { title: "Hip Hop" },
  { title: "Skincare" },
  { title: "J-Pop" },
  { title: "Shisha" },
  { title: "Cricket" },
  { title: "Korean Dramas" },
  { title: "Freelance" },
  { title: "K-Pop" },
  { title: "Skateboarding" },
  { title: "Gospel" },
  { title: "Group X" },
  { title: "Potterhead" },
  { title: "Trying New Things" },
  { title: "Photography" },
  { title: "Bollywood" },
  { title: "Reading" },
  { title: "Singing" },
  { title: "Sports" },
  { title: "Poetry" },
  { title: "Stand up Comedy" },
  { title: "Coffee" },
  { title: "Karaoke" },
  { title: "Fortnite" },
  { title: "Free Diving" },
  { title: "Self Development" },
  { title: "Mental Health Awareness" },
  { title: "Foodie Tour" },
  { title: "Voter Rights" },
  { title: "Jiu-jitsu" },
  { title: "Climate Change" },
  { title: "Exhibition" },
  { title: "Walking My Dog" },
  { title: "LGBTQIA+ Rights" },
  { title: "Feminism" },
  { title: "VR Room" },
  { title: "Escape Cafe" },
  { title: "Shopping" },
  { title: "Brunch" },
  { title: "Investment" },
  { title: "Jetski" },
  { title: "Reggaeton" },
  { title: "Second-hand apparel" },
  { title: "Black Lives Matter" },
  { title: "Jogging" },
  { title: "Road Trips" },
  { title: "Vintage fashion" },
  { title: "Voguing" },
  { title: "Couchsurfing" },
  { title: "Happy hour" },
  { title: "Inclusivity" },
  { title: "Country Music" },
  { title: "Football" },
  { title: "Inline Skate" },
  { title: "Investing" },
  { title: "Tennis" },
  { title: "Ice Cream" },
  { title: "Ice Skating" },
  { title: "Human Rights" },
  { title: "Expositions" },
  { title: "Pig Roast" },
  { title: "Skiing" },
  { title: "Canoeing" },
  { title: "West End Musicals" },
  { title: "Snowboarding" },
  { title: "Pilates" },
  { title: "Pentathlon" },
  { title: "Broadway" },
  { title: "PlayStation" },
  { title: "Cheerleading" },
  { title: "Choir" },
  { title: "Pole Dancing" },
  { title: "Five-a-side Football" },
  { title: "Car Racing" },
  { title: "Pinterest" },
  { title: "Festivals" },
  { title: "Pub Quiz" },
  { title: "Catan" },
  { title: "Cosplay" },
  { title: "Motor Sports" },
  { title: "Coffee Stall" },
  { title: "E-Sports" },
  { title: "Content Creation" },
  { title: "Bicycle Racing" },
  { title: "Binge-Watching TV shows" },
  { title: "Songwriter" },
  { title: "Bodycombat" },
  { title: "Tattoos" },
  { title: "Painting" },
  { title: "Bodyjam" },
  { title: "Paddle Boarding" },
  { title: "Padel" },
  { title: "Blackpink" },
  { title: "Surfing" },
  { title: "Bowling" },
  { title: "Grime" },
  { title: "90s Britpop" },
  { title: "Bodypump" },
  { title: "Beach Bars" },
  { title: "Bodystep" },
  { title: "Paragliding" },
  { title: "Upcycling" },
  { title: "V-Pop" },
  { title: "Equality" },
  { title: "Astrology" },
  { title: "Motorcycles" },
  { title: "Equestrian" },
  { title: "Bun cha" },
  { title: "Entrepreneurship" },
  { title: "Sake" },
  { title: "BTS" },
  { title: "Cooking" },
  { title: "Environmental Protection" },
  { title: "Fencing" },
  { title: "Soccer" },
  { title: "Saxophonist" },
  { title: "Sci-Fi" },
  { title: "Dancing" },
  { title: "Film Festival" },
  { title: "Freeletics" },
  { title: "Gardening" },
  { title: "Amateur Cook" },
  { title: "Exchange Program" },
  { title: "Sauna" },
  { title: "Art" },
  { title: "Politics" },
  { title: "Flamenco" },
  { title: "Museum" },
  { title: "Activism" },
  { title: "Running Man" },
  { title: "DAOs" },
  { title: "Real Estate" },
  { title: "Podcasts" },
  { title: "Disability Rights" },
  { title: "Rap Viet" },
  { title: "Rave" },
  { title: "Pimms" },
  { title: "BBQ" },
  { title: "Drive Thru Cinema" },
  { title: "Rock Climbing" },
  { title: "Craft Beer" },
  { title: "Iced Tea" },
  { title: "Drummer" },
  { title: "Tea" },
  { title: "Board Games" },
  { title: "Roblox" },
  { title: "Pubs" },
  { title: "Rock" },
  { title: "Tango" },
  { title: "Drawing" },
  { title: "Trivia" },
  { title: "Pho" },
  { title: "Volunteering" },
  { title: "Environmentalism" },
  { title: "Rollerskating" },
  { title: "Wine" },
  { title: "Dungeons & Dragons" },
  { title: "Hot Pot" },
  { title: "Vlogging" },
  { title: "Electronic Music" },
  { title: "Ramen" },
  { title: "Weightlifting" },
  { title: "Live Music" },
  { title: "Writing" },
  { title: "Xbox" },
  { title: "World Peace" },
  { title: "Wrestling" },
  { title: "Literature" },
  { title: "Manga" },
  { title: "Pride" },
  { title: "Marathon" },
  { title: "Makeup" },
  { title: "Youth Empowerment" },
  { title: "YouTube" },
  { title: "Martial Arts" },
  { title: "Marvel" },
  { title: "Vegan Cooking" },
  { title: "Vermut" },
  { title: "Korean Food" },
  { title: "Twitter" },
  { title: "Volleyball" },
  { title: "Walking Tour" },
  { title: "Vinyasa" },
  { title: "Virtual Reality" },
  { title: "League of Legends" },
  { title: "NFTs" },
  { title: "Bar Hopping" },
  { title: "Nintendo" },
  { title: "Baseball" },
  { title: "Parties" },
  { title: "Ballet" },
  { title: "Band" },
  { title: "Online Games" },
  { title: "Battle Ground" },
  { title: "Beach Tennis" },
  { title: "Nightlife" },
  { title: "Online Shopping" },
  { title: "Sailing" },
  { title: "Olympic Gymnastics" },
  { title: "Bassist" },
  { title: "Online Broker" },
  { title: "Military" },
  { title: "Memes" },
  { title: "Among Us" },
  { title: "Motorbike Racing" },
  { title: "Muay Thai" },
  { title: "Motorcycling" },
  { title: "Metaverse" },
  { title: "Mindfulness" },
  { title: "Acapella" },
  { title: "Musical Instrument" },
  { title: "Art galleries" },
  { title: "Musical Writing" },
  { title: "Hiking" },
  { title: "Artistic Gymnastics" },
  { title: "Mountains" },
  { title: "Archery" },
  { title: "Atari" },
  { title: "Backpacking" },
  { title: "Fishing" },
  { title: "Clubbing" },
  { title: "Street Food" },
  { title: "Crossfit" },
  { title: "Concerts" },
  { title: "Climbing" },
  { title: "Baking" },
  { title: "Camping" },
  { title: "Blogging" },
  { title: "Collecting" },
  { title: "Cars" },
  { title: "Start ups" },
  { title: "Boba tea" },
  { title: "High School Sports" },
  { title: "Badminton" },
  { title: "Active Lifestyle" },
  { title: "Fashion" },
  { title: "Anime" },
  { title: "NBA" },
  { title: "MLB" },
  { title: "Funk music" },
  { title: "Caipirinha" },
  { title: "Indoor Activities" },
  { title: "Tempeh" },
  { title: "DIY" },
  { title: "Town Festivities" },
  { title: "Cycling" },
  { title: "Outdoors" },
  { title: "TikTok" },
  { title: "Picnicking" },
  { title: "Twitch" },
  { title: "Comedy" },
  { title: "Trap Music" },
  { title: "Music" },
  { title: "Triathlon" },
  { title: "Netflix" },
  { title: "Disney" },
  { title: "Rugby" },
  { title: "Açaí" },
  { title: "Samba" },
  { title: "Tarot" },
  { title: "Stock Exchange" },
  { title: "Stocks" },
  { title: "Swimming" },
  { title: "Table Tennis" },
  { title: "Killing time" },
  { title: "Working out" },
  { title: "Yoga" },
  { title: "Horror Movies" },
  { title: "Boxing" },
  { title: "Bar Chilling" },
];
export default InterestingItems;
